// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEt7rryjfb-VMQ9sWNDtU8ikjygdg10SM',
    appId: '1:729032745242:web:408c5100e2e530003f0ca3',
    messagingSenderId: '729032745242',
    projectId: 'anigame-a8b61',
    authDomain: 'anigame-a8b61.firebaseapp.com',
    storageBucket: 'anigame-a8b61.firebasestorage.app',
    measurementId: 'G-RNXHTNCJZS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBugvk4HhE_T2zQJbuc_7oogYVI4RDK2CU',
    appId: '1:729032745242:android:072b165ef425a16e3f0ca3',
    messagingSenderId: '729032745242',
    projectId: 'anigame-a8b61',
    storageBucket: 'anigame-a8b61.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBfV21jVEpdiuorAA5Xm6oGLHqe3KHMm54',
    appId: '1:729032745242:ios:269885e5d4fb7c3a3f0ca3',
    messagingSenderId: '729032745242',
    projectId: 'anigame-a8b61',
    storageBucket: 'anigame-a8b61.firebasestorage.app',
    iosBundleId: 'com.example.anigame',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBfV21jVEpdiuorAA5Xm6oGLHqe3KHMm54',
    appId: '1:729032745242:ios:269885e5d4fb7c3a3f0ca3',
    messagingSenderId: '729032745242',
    projectId: 'anigame-a8b61',
    storageBucket: 'anigame-a8b61.firebasestorage.app',
    iosBundleId: 'com.example.anigame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBEt7rryjfb-VMQ9sWNDtU8ikjygdg10SM',
    appId: '1:729032745242:web:c4750429cc27bab23f0ca3',
    messagingSenderId: '729032745242',
    projectId: 'anigame-a8b61',
    authDomain: 'anigame-a8b61.firebaseapp.com',
    storageBucket: 'anigame-a8b61.firebasestorage.app',
    measurementId: 'G-DKG5FK7CDB',
  );

}